In [20]:
import pandas as pd
from scipy.sparse import hstack  
link1="S:\\ML\\Kaggle_dataset\\gamesset\\steam_games.csv"
data1=pd.read_csv(link1)
link2="S:\\ML\\Kaggle_dataset\\gamesset\steam_games_reviews.csv"
data2=pd.read_csv(link2)
df=pd.merge(data1,data2, on="app_id")

C:\Users\SAYAN\AppData\Local\Temp\ipykernel_3432\2610131856.py:4: DtypeWarning: Columns (0: windows, 1: mac, 2: linux) have mixed types. Specify dtype option on import or set low_memory=False.
  data1=pd.read_csv(link1)

In [21]:
df=df.drop(columns=["notes","movies","website","support_url","support_email","metacritic_url","screenshots","short_description","about_the_game","header_image","full_audio_languages"])
df

,app_id,name_x,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,dlc_count,packages,supported_languages,windows,mac,linux,steam_store_available,steam_spy_available,name_y,reviews
0,876320,Hyperspace Delivery Service,2019-06-05,9.99,paid,0 - 20000,"[""Zotnip""]","[""Zotnip""]","[""Action"", ""Adventure"", ""Indie"", ""Simulation"",...","[""Single-player"", ""Steam Achievements"", ""Full ...",...,1,"[{""title"": ""Buy Hyperspace Delivery Service"", ...","[""English""]",True,True,True,True,True,Hyperspace Delivery Service,“...this looks like the kind of thing that wou...
1,876500,HyperDot,2020-01-30,19.99,paid,50000 - 100000,"[""Tribe Games""]","[""GLITCH""]","[""Action"", ""Casual"", ""Indie""]","[""Single-player"", ""Multi-player"", ""PvP"", ""Shar...",...,1,"[{""title"": ""Buy HyperDot"", ""description"": """", ...","[""English""]",True,True,True,True,True,HyperDot,"“Easy to learn, but maddeningly cerebrum-busti..."
2,876840,999,2018-06-29,9.99,paid,0 - 20000,"[""Tydecon Games""]","[""Tydecon Games""]","[""Casual"", ""Indie""]","[""Single-player"", ""Steam Achievements"", ""Steam...",...,0,"[{""title"": ""Buy 999"", ""description"": """", ""subs...","[""English""]",True,False,False,True,True,999,“A game about literally throwing your head off...
3,876850,WhiteLily 1：丽丽公主,2018-08-16,2.99,paid,20000 - 50000,"[""游学者狐狸""]","[""游学者狐狸""]","[""Adventure"", ""Casual"", ""Indie"", ""RPG"", ""Strat...","[""Single-player"", ""Steam Achievements"", ""Steam...",...,1,"[{""title"": ""Buy WhiteLily 1：丽丽公主"", ""descriptio...","[""Simplified Chinese""]",True,False,False,True,True,WhiteLily 1：丽丽公主,“这款游戏在玩法上属于角色扮演，在游戏性上以剧情为主，同时包含一些解谜元素和少量的回合制战斗...
4,877040,Samurai Wish,2018-09-12,2.99,paid,0 - 20000,"[""Grégory Joerger""]","[""Grégory Joerger""]","[""Action"", ""Indie""]","[""Single-player"", ""Steam Achievements"", ""Full ...",...,1,"[{""title"": ""Buy Samurai Wish"", ""description"": ...","[""English""]",True,False,False,True,True,Samurai Wish,“I thought this is another trash game. Instead...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13077,2545,RIP - Trilogy™,2007-06-01,4.99,paid,"100,000 .. 200,000","[""Elephant Games""]",[],"[{""id"": ""4"", ""description"": ""Casual""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,[346],English,True,False,False,True,True,RIP - Trilogy™,GameTunnel gives RIP 3 a 73% 'The RIP series i...
13078,2550,RIP - Trilogy™,2007-06-01,4.99,paid,"100,000 .. 200,000","[""Elephant Games""]",[],"[{""id"": ""4"", ""description"": ""Casual""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,[346],English,True,False,False,True,True,RIP - Trilogy™,GameTunnel gives RIP 3 a 73% 'The RIP series i...
13079,4240,RACE - The WTCC Game,2006-11-24,39.99,paid,"200,000 .. 500,000","[""SimBin""]","[""SimBin""]","[{""id"": ""9"", ""description"": ""Racing""}]","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,[18370],"English, French, German, Italian, Spanish - Spain",True,False,False,True,True,RACE - The WTCC Game,[]
13080,4932,Natural Selection 2,2012-10-30,4.99,paid,"0 .. 20,000","[""Unknown Worlds Entertainment""]","[""Unknown Worlds Entertainment"", ""KRAFTON, Inc.""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 1, ""description"": ""Multi-player""}, {""i...",...,10,"[17843, 372372, 16496, 17844, 25983]","English<strong>*</strong>, French, German, Spa...",True,False,False,True,True,Natural Selection 2,[]
13081,6129,Shank,2010-10-25,9.99,paid,"0 .. 20,000","[""Klei Entertainment""]","[""Klei Entertainment""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,[6321],English<strong>*</strong><br><strong>*</strong...,True,True,True,True,True,Shank,[]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer as feed
vector=feed() 
x1=df[["name_x","price_status","estimated_owners","developers","publishers","genres","categories","tags","detailed_description","packages","supported_languages","windows","mac","linux","steam_spy_available","name_y"]]
x2=vector.fit_transform(x1)
x2

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 16 stored elements and shape (16, 16)>

In [36]:
x3=df[["price","positive","negative","recommendations","peak_ccu","metacritic_score","average_playtime_forever","median_playtime_forever","achievements"]]
x3

,price,positive,negative,recommendations,peak_ccu,metacritic_score,average_playtime_forever,median_playtime_forever,achievements
0,9.99,42,4,0.0,0,0.0,0,0,20.0
1,19.99,32,5,0.0,0,0.0,0,0,26.0
2,9.99,7,9,0.0,0,0.0,0,0,126.0
3,2.99,1135,71,191.0,0,0.0,0,0,21.0
4,2.99,14,4,0.0,0,0.0,0,0,57.0
...,...,...,...,...,...,...,...,...,...
13077,4.99,204,136,249.0,0,NaN,0,0,NaN
13078,4.99,204,136,249.0,0,NaN,0,0,NaN
13079,39.99,121,42,NaN,0,NaN,0,0,NaN
13080,4.99,8827,1539,8619.0,0,80.0,0,0,137.0
13081,9.99,1884,240,3004.0,0,67.0,0,0,12.0

In [27]:
y1=df["reviews"]
y=vector.fit_transform(y1)
y

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 538854 stored elements and shape (13082, 36285)>

In [37]:
from sklearn.model_selection import train_test_split as ttp
x_train,x_test,y_train,y_test=ttp(x2,y,train_size=0.70,random_state=45,shuffle=True)

ValueError: Found input variables with inconsistent numbers of samples: [16, 13082]